### ISSUE TITLE
Recall and precision on ICDAR2013

### ISSUE THREAD

**Issue by lyc6749** [autonise/CRAFT-Remade#19]
How about the recall and precision on ICDAR2013 by your implemention？

**Comment by lyc6749** [comment]
![image](https://user-images.githubusercontent.com/33708958/63691886-f6788100-c842-11e9-8620-f15389d3842c.png)
Can you provide this file？

**Comment by mayank-git-hub** [comment]
Hey, Sorry for the delayed reply. I have been sick for a few days. Will solve the bugs in the master by the end of the day. Thank You for your patience.

**Comment by mayank-git-hub** [comment]
> How about the recall and precision on ICDAR2013 by your implemention？

The weak supervision code seems to be working. I have updated the master branch to incorporate the changes. I will train the model tomorrow on IC13, IC15 and send the link to the pre-trained model, Generated character Bounding Boxes, and F-score.

Thank You for your patience.

**Comment by lianqing11** [comment]
Hi @mayank-git-hub , thanks for your code. Do you mind telling me that what is the performance of the pre-trained model on ICDAR 13 dataset?

**Comment by mayank-git-hub** [comment]
Currently the performance is not good. I am able to achieve an approximate F-score of 70. I am tweaking and experimenting to improve the results. Will update the ReadMe file with the F-scores of all the datasets.

**Comment by lianqing11** [comment]
Thanks for your reply. I am also working on the training code. And also only could get 0.71 H-mean on IC13 dataset.  Looking for your results.

**Comment by mayank-git-hub** [comment]
Great, I am also working on it. Would update the Readme file as soon as I get better results. Thank You for your patience.

**Comment by lamhoangtung** [comment]
@mayank-git-hub Quick question, 0.7051 F1 Score on IC13 is with CRAFT or ResNet CRAFT ? Which one is better and by how much ?

Thanks ;)

**Comment by mayank-git-hub** [comment]
The f score is with craft model with vgg backbone. Haven't tried resnet unet architecture.

**Comment by lamhoangtung** [comment]
Thanks @mayank-git-hub. Btw, I saw you included link to Original Model by authors in the README. Can we load that model and fine tune it with this code ?

**Comment by lamhoangtung** [comment]
> Thanks @mayank-git-hub. Btw, I saw you included link to Original Model by authors in the README. Can we load that model and fine tune it with this code ?

Yep we can ;)

**Comment by mayank-git-hub** [comment]
Yep
