### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by lyc6749** [autonise/CRAFT-Remade#2]
![image](https://user-images.githubusercontent.com/33708958/62459119-26d37f00-b7b1-11e9-8ba7-bd2f4b31878a.png)

when will you upload these model files？

**Comment by mayank-git-hub** [comment]
https://drive.google.com/open?id=1YBOjhyYweM9im_syfOChUoP57lEhrH35

**Comment by vallimangai** [comment]
What was the format of dataset?
