### ISSUE TITLE
Invalid Mode `synthesize`

### ISSUE THREAD

**Issue by deepseek** [autonise/CRAFT-Remade#21]
@mayank-git-hub 
When running:
`python main.py train-synth --mode=synthesize --model=./model/final.pkl --folder=./input`

It seems that you didn't add an actual `synthesize` mode in `main.py`.

Note: replace `train_synth` with `train-synth` in `README`

**Comment by mayank-git-hub** [comment]
Hey @deepseek . For generating the bbox on your own images, you should use the command -
`python main.py synthesize --model=./model/final.pkl --folder=./input`

I have updated the ReadMe.md for the same.

If you are using `click==6.7` then it should be train_synth, for higher versions of click, the _ has been replaced with -.
