### ISSUE TITLE
Getting wrong target_affinity when training SynthText style dataset

### ISSUE THREAD

**Issue by lamhoangtung** [autonise/CRAFT-Remade#25]
Hi. Thanks for the great work. I'm trying to train this code on my own generated dataset, which is a SynthText style dataset for Japanese.

The code seem running but I've been noticed in the debug folder that the `target_affinity.png` file is just a black while `target_characters.png` seem correct.

Image:
![image](https://user-images.githubusercontent.com/26834698/64157910-c4c67200-ce61-11e9-90bd-ed751ec68f12.png)

Target affinity:
![target_affinity](https://user-images.githubusercontent.com/26834698/64157928-cc861680-ce61-11e9-9bab-2e295d94d328.png)

Target character heat map:
![target_characters](https://user-images.githubusercontent.com/26834698/64157934-ce4fda00-ce61-11e9-818c-813c9189516f.png)

Do you have any suggestion what might be wrong here ? You can see my code in my fork, it's pretty much identical to yours (I only created a new data loader :P)

**Comment by mayank-git-hub** [comment]
I can't say surely without running the code on your dataset, but there should not be any reason for this happening if the character heat map is being generated correctly. 

Does this happen just on this particular image or all images?

I am not able to reproduce it using the SynthText dataset I have available.

**Comment by lamhoangtung** [comment]
Hmm, this is happening to all images.

Btw, what is the type of `self.txt` in class `DataLoaderSYNTH` that your `generate_affinity` function expect? ;_;

**Comment by lamhoangtung** [comment]
Some interesting update on this bug :P, the target affinity appear to be wrong on other images (not empty) for example while the target characters remain correct :3

Image:
![image](https://user-images.githubusercontent.com/26834698/64190511-c4999700-cea0-11e9-9c43-04880f05978d.png)

Target affinity:
![target_affinity](https://user-images.githubusercontent.com/26834698/64190520-c95e4b00-cea0-11e9-985d-f58cafef0337.png)

Target character heat map:
![target_characters](https://user-images.githubusercontent.com/26834698/64190496-be0b1f80-cea0-11e9-9336-a7e22fefcfe1.png)

**Comment by mayank-git-hub** [comment]
self.txt is a list like - 
[ ['words', 'in', 'sample', 'one'], ['words', 'in', 'sample', two']] 

Hmm, Can you confirm if the affinity is wrong, or whether only some of them are drawn, while others are being discarded by the .is_valid check in src/utils/data_manipulation.py

**Comment by mayank-git-hub** [comment]
I am finding a lot of affinity samples not passing the valid polygon test. Looking into why that is happening.

**Comment by lamhoangtung** [comment]
> self.txt is a list like -
> [ ['words', 'in', 'sample', 'one'], ['words', 'in', 'sample', two']]
> 
> Hmm, Can you confirm if the affinity is wrong, or whether only some of them are drawn, while others are being discarded by the .is_valid check in src/utils/data_manipulation.py

Damn, my first mistake is keep using `+=` when pre-process self.txt, I changed to `append` and now it working as expected.

But now I found some other interesting stuff happen :3.

For example:

Image:
![image](https://user-images.githubusercontent.com/26834698/64191799-789c2180-cea3-11e9-90ab-e0280eb64be7.png)

Target Affinity:
![target_affinity](https://user-images.githubusercontent.com/26834698/64191820-8782d400-cea3-11e9-9ea1-6c7821cdeba6.png)

Target Characters:
![target_characters](https://user-images.githubusercontent.com/26834698/64191832-8e114b80-cea3-11e9-84eb-b787315afe94.png)

Is this Target Affinity consider correct ?
![target_affinity 2](https://user-images.githubusercontent.com/26834698/64191908-bef18080-cea3-11e9-9e54-d4bdd1a4d19b.png)

Since I saw a link from the first line to the second line ?

**Comment by mayank-git-hub** [comment]
umm, looks like these two words have been taken to be one word in the self.txt. 

Could you confirm if that is the case? 

Also there is a bug in order_points because of which some affinity bbox are being lost. The order_points would work for rectangles, but not for quadilaterals. I am fixing the issue.

**Comment by mayank-git-hub** [comment]
You should remove all the uses of order_points in your fork. It is unnecessary(I had used this code from another source where the order matters, but in our case due to the gaussian heatmap being isotropic, it won't) and does not actually order the points.

**Comment by lamhoangtung** [comment]
> umm, looks like these two words have been taken to be one word in the self.txt.
> 
> Could you confirm if that is the case?
> 
> Also there is a bug in order_points because of which some affinity bbox are being lost. The order_points would work for rectangles, but not for quadilaterals. I am fixing the issue.

That's true. Seem like this is a bugs in my generated data ;_;

**Comment by mayank-git-hub** [comment]
Cool, Thanx for bringing this bug to attention!
