### ISSUE TITLE
utils_old.py

### ISSUE THREAD

**Issue by nightfuryyy** [autonise/CRAFT-Remade#36]
Thank you for awsome repo. 
Why not you use the code in utils_old.py ?
Thank you.

**Comment by mayank-git-hub** [comment]
Glad that you liked the repo,

utils_old.py contains data augmentation and a different way of connecting the characters and affinity.

I was trying to reproduce the paper, hence I had left it for future usage.

**Comment by nightfuryyy** [comment]
so can i use your data augmentation without change it ?

**Comment by mayank-git-hub** [comment]
I have not tested it, but you can obviously give it a try.

**Comment by nightfuryyy** [comment]
thanks for your reply
