### ISSUE TITLE
RuntimeError: DataLoader worker (pid 4249) is killed by signal: Killed. 

### ISSUE THREAD

**Issue by alinesoares1** [autonise/CRAFT-Remade#37]
![Sem título](https://user-images.githubusercontent.com/54413027/89963867-2751f180-dc1f-11ea-972e-cb9348e66649.png)

How can I solve this? I am using Colab to train CRAFT model but I have just one GPU available.

**Comment by mayank-git-hub** [comment]
Hey, can you run the dataloader with 0 workers, that will make the dataloader synchronous and give better error logs.
