### ISSUE TITLE
Weak Supervision Training

### ISSUE THREAD

**Issue by alikaz3mi** [autonise/CRAFT-Remade#41]
Hello, I would like to know whether it is possible to only train on weak supervision. During weak supervision main, it reads some configs from train_synth:
pretrained_path = '/home/SharedData/Mayank/Models/SYNTH/6000_model.pkl'
pretrained_loss_plot_training = '/home/SharedData/Mayank/Models/SYNTH/loss_plot_training.npy'

Should I worry about these?

**Comment by mayank-git-hub** [comment]
Hello @alikaz3mi sorry for the late reply.

These config variables point to the pre-trained models which we get during strong supervision. If you want to start from scratch directly on the weak supervision task, you can just store a randomly initialized model file and update the config paths.

Or it will be better if you comment out the pretrained model loader code in weak supervision function.
