### ISSUE TITLE
Error: No such command 'train_synth'.

### ISSUE THREAD

**Issue by alternativebug** [autonise/CRAFT-Remade#48]
According to the [docs](https://github.com/autonise/CRAFT-Remade#:~:text=python%20main.py%20train_synth), to train from scratch, I run:

    python3 CRAFT-Remade/main.py train_synth

I get:

    Usage: main.py [OPTIONS] COMMAND [ARGS]...
    Try 'main.py --help' for help.
    
    Error: No such command 'train_synth'.

**Comment by mayank-git-hub** [comment]
Hello @schissmantics , I think the error is due to you running the code from a different base path. I think if you run it from inside the directory CRAFT-Remade, you should not get such an error.

**Comment by ghost** [comment]
I still get the same error inside dir

**Comment by yeonsikch** [comment]
try `main.py train-synth` instead of `main.py train_synth`.

**Comment by mayank-git-hub** [comment]
The click version affects whether you should use train-synth or train_synth. Thank you @yeonsikch for pointing that out.
