### ISSUE TITLE
Paths in a train_synth/config.py point to a Google drive directory that is not shared.

### ISSUE THREAD

**Issue by mobinamosannafat** [autonise/CRAFT-Remade#49]
Hi, when I run this command "!python main.py train-synth" I get this error: 

FileNotFoundError: [Errno 2] No such file or directory: '/home/SharedData/Mayank/Models/SYNTH/config.py'

In addition, in file config.py, in the main directory, a series of paths have been read that appear to be in your system. for example :
DataLoaderSYNTH_mat = '/home/SharedData/Mayank/SynthText/gt.mat'
Is it possible for you to share this data?

**Comment by yeonsikch** [comment]
Hi.

u can get it from this [page](https://www.robots.ox.ac.uk/~vgg/data/scenetext/).
good luck.

**Comment by mayank-git-hub** [comment]
As mentioned by @yeonsikch , you can find the SYNTH Text data on https://www.robots.ox.ac.uk/~vgg/data/scenetext/ . 

As for the FileNotFoundError, you need to set the path where the model files will be stored in train_synth/config.py
