### ISSUE TITLE
gt.mat file

### ISSUE THREAD

**Issue by bart-khalid** [autonise/CRAFT-Remade#53]
I am trying to train weak-supervision on IC13 dataset and I don't know where to find gt.mat file that is mentionned in the config.py ?
the error I'm getting : `FileNotFoundError: [Errno 2] No such file or directory: '/home/SharedData/Mayank/SynthText/gt.mat'`

**Comment by mayank-git-hub** [comment]
This file is needed for strong supervision task. You will need to download the synthtext dataset to get the file.
