### ISSUE TITLE
strong train path

### ISSUE THREAD

**Issue by dotrungkien3210** [autonise/CRAFT-Remade#55]
in train_synth i see pretrained_path and loss_plot_training.npy, can you help me how to download it or how to generate it

**Comment by mayank-git-hub** [comment]
If you have set pretrained=False, you don't require the pretrained_path and the loss_plot_training.npy.

You can generate it by training the model with strong supervision.

The details on how to train using strong supervision on the synthtext dataset is detailed in the readme file.

A link to the pre-trained model on synthtext dataset is also provided in the readme file.
